apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"jellyfin","namespace":"jellyfin"},"spec":{"ports":[{"name":"http","port":8096,"targetPort":8096}],"selector":{"app":"jellyfin"}}}
  creationTimestamp: "2025-11-26T14:43:53Z"
  name: jellyfin
  namespace: jellyfin
  resourceVersion: "539085"
  uid: ab7d1eef-2e52-4195-a80f-ec0095e625c2
spec:
  clusterIP: 10.43.5.95
  clusterIPs:
  - 10.43.5.95
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app: jellyfin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
